"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    nav_home: "Home",
    nav_library: "Library",
    nav_collection: "Vault",
    nav_wishlist: "Wishlist",
    nav_picker: "Picker",
    
    // Vault / Collection
    vault_title: "My Vault",
    vault_subtitle: "Fragrances Owned",
    vault_empty: "Your collection is empty.",
    add_to_vault: "Add to Vault",
    edit_details: "Edit Details",
    opening_date: "Opening Date",
    remaining_level: "Remaining Level",
    format: "Format",
    days_open: "days",
    oxidation_index: "Oxidation Index",
    
    // Discovery / Wishlist
    discovery_title: "My Discovery",
    discovery_subtitle: "Scents to Explore",
    discovery_empty: "Your discovery list is empty.",
    to_test: "To Test",
    archived: "Archived",
    rate_experience: "Rate Experience",
    verdict: "Verdict",
    sillage: "Sillage",
    longevity: "Longevity",
    
    // Scent Picker
    picker_title: "Scent Picker",
    picker_subtitle: "Tailored recommendations for your day.",
    weather_outside: "Weather Outside",
    your_mood: "Your Current Mood",
    find_signature: "Find My Signature Scent",
    analyzing: "Analyzing collection...",
    recommended_picks: "Recommended Picks",
    outside_temp: "Outside Temperature",
    
    mood_energetic: "Energetic",
    mood_romantic: "Romantic",
    mood_casual: "Casual",
    mood_formal: "Formal",
    mood_fresh: "Fresh",
    mood_cozy: "Cozy",
    
    weather_sunny: "Sunny",
    weather_cloudy: "Cloudy",
    weather_rainy: "Rainy",
    weather_snowy: "Snowy",
    weather_stormy: "Stormy",
    
    // General
    search_library: "Search the library...",
    add_manually: "Add Manually",
    cancel: "Cancel",
    save: "Save Changes",
    delete: "Delete",
    sign_in: "Sign In",
    brand: "Brand / House",
    name: "Name",
    rating: "Rating",
    library_title: "The Library",
    library_subtitle: "Browse through our curated collection of world-class fragrances.",
    loading_more: "Scrolling for more scents...",
    end_of_collection: "You've reached the end of the collection",
    no_fragrances: "No fragrances found.",
    clear_filters: "Clear filters",
    top_notes: "Top Notes",
    middle_notes: "Middle Notes",
    base_notes: "Base Notes",
    main_accords: "Main Accords",
    release_year: "Release Year",
    gender: "Gender",
    men: "Men",
    women: "Women",
    unisex: "Unisex",
    all: "All",
    added_to_vault: "Added to Vault",
    added_to_wishlist: "Added to Wishlist",
    oxidation_high: "High Oxidation",
    oxidation_mod: "Moderate Oxidation",
    oxidation_stable: "Stable",
    scent_profile: "Scent Profile",
    perfumer_phrase: "The nose behind this fragrance is",
    // Accords mapping
    "warm spicy": "Warm Spicy",
    "fresh spicy": "Fresh Spicy",
    "woody": "Woody",
    "aromatic": "Aromatic",
    "vanilla": "Vanilla",
    "citrus": "Citrus",
    "powdery": "Powdery",
    "floral": "Floral",
    "white floral": "White Floral",
    "musky": "Musky",
    "sweet": "Sweet",
    "amber": "Amber",
    "balsamic": "Balsamic",
    "green": "Green",
    "fruity": "Fruity",
    "aquatic": "Aquatic",
    "earthy": "Earthy",
    "patchouli": "Patchouli",
    "leather": "Leather",
    "oud": "Oud",
    "rose": "Rose",
    "smoky": "Smoky",
    "animalic": "Animalic",
    "yellow floral": "Yellow Floral",
    "tuberose": "Tuberose",
    "coniferous": "Coniferous",
    "mossy": "Mossy",
    // Notes mapping
    "lavender": "Lavender",
    "bergamot": "Bergamot",
    "mandarin orange": "Mandarin Orange",
    "jasmine": "Jasmine",
    "sandalwood": "Sandalwood",
    "cedar": "Cedar",
    "musk": "Musk",
    "lemon": "Lemon",
    "apple": "Apple",
    "pink pepper": "Pink Pepper",
    "cardamom": "Cardamom",
    "vetiver": "Vetiver",
    "tonka bean": "Tonka Bean",
    "neroli": "Neroli",
    "violet": "Violet",
    "geranium": "Geranium",
    "incense": "Incense",
    "saffron": "Saffron",
    "cinnamon": "Cinnamon",
    "ginger": "Ginger",
    "grapefruit": "Grapefruit",
    "pear": "Pear",
    "peach": "Peach",
    "raspberry": "Raspberry",
    "black currant": "Black Currant",
    "mint": "Mint",
    "basil": "Basil",
    "sage": "Sage",
    "rosemary": "Rosemary",
    "oakmoss": "Oakmoss",
    "tobacco": "Tobacco",
    "coffee": "Coffee",
    "chocolate": "Chocolate",
    "honey": "Honey",
    "sea salt": "Sea Salt",
    "coconut": "Coconut",
    "pineapple": "Pineapple",
    "cherry": "Cherry",
    "orange blossom": "Orange Blossom",
    "lily-of-the-valley": "Lily-of-the-valley",
    "benzoin": "Benzoin",
    "myrrh": "Myrrh",
    "rhubarb": "Rhubarb",
    "fig": "Fig",
    "petitgrain": "Petitgrain",
    "clary sage": "Clary Sage",
    "coriander": "Coriander",
    "nutmeg": "Nutmeg",
    "cloves": "Cloves",
    "star anise": "Star Anise",
    "licorice": "Licorice",
    "rum": "Rum",
    "guaiac wood": "Guaiac Wood",
    "birch": "Birch",
    "oak": "Oak",
    "almond": "Almond",
    "pistachio": "Pistachio",
    "hazelnut": "Hazelnut",
    "tea": "Tea",
    "black tea": "Black Tea",
    "green tea": "Green Tea",
  },
  fr: {
    // Navigation
    nav_home: "Accueil",
    nav_library: "Bibliothèque",
    nav_collection: "Collection",
    nav_wishlist: "Wishlist",
    nav_picker: "Sélecteur",
    
    // Vault / Collection
    vault_title: "Ma Collection",
    vault_subtitle: "Parfums possédés",
    vault_empty: "Votre collection est vide.",
    add_to_vault: "Ajouter à la Collection",
    edit_details: "Modifier les détails",
    opening_date: "Date d'ouverture",
    remaining_level: "Niveau restant",
    format: "Format",
    days_open: "j",
    oxidation_index: "Indice d'Oxydation",
    add_perfume: "Ajouter un parfum",
    save: "Enregistrer",
    brand: "Marque",
    name: "Nom",
    add_manually: "Ajouter manuellement",
    cancel: "Annuler",
    hero_title_1: "Sublimez votre",
    hero_title_2: "Voyage Olfactif",
    hero_desc: "ScentLibrary est votre cabinet digital premium pour suivre, découvrir et organiser votre collection de parfums. Du premier spray au sillage final.",
    btn_explore: "Explorer la Bibliothèque",
    btn_collection: "Ma Collection",
    feature_1_title: "Bibliothèque Étendue",
    feature_1_desc: "Recherchez parmi une base de données riche. Consultez les notes, les accords et les avis.",
    feature_2_title: "Suivi d'Oxydation",
    feature_2_desc: "Surveillez la macération de votre collection pour savoir quand un parfum atteint son apogée.",
    feature_3_title: "Scent Picker",
    feature_3_desc: "Laissez l'intelligence artificielle choisir votre parfum selon la météo et votre humeur.",
    
    // Discovery / Wishlist
    discovery_title: "Mes Découvertes",
    discovery_subtitle: "Parfums à explorer",
    discovery_empty: "Votre liste de découvertes est vide.",
    to_test: "À Tester",
    archived: "Archivé",
    rate_experience: "Noter l'expérience",
    verdict: "Verdict",
    sillage: "Sillage",
    longevity: "Tenue",
    
    // Scent Picker
    picker_title: "Scent Picker",
    picker_subtitle: "Des recommandations sur mesure pour votre journée.",
    weather_outside: "Météo Extérieure",
    your_mood: "Votre Humeur actuelle",
    find_signature: "Trouver mon Parfum du Jour",
    analyzing: "Analyse de la collection...",
    recommended_picks: "Sélection Recommandée",
    outside_temp: "Température Extérieure",

    mood_energetic: "Energique",
    mood_romantic: "Romantique",
    mood_casual: "Décontracté",
    mood_formal: "Formel",
    mood_fresh: "Frais",
    mood_cozy: "Cocon",
    
    weather_sunny: "Ensoleillé",
    weather_cloudy: "Nuageux",
    weather_rainy: "Pluvieux",
    weather_snowy: "Neigeux",
    weather_stormy: "Orageux",
    
    // General
    search_library: "Chercher dans la bibliothèque...",
    add_manually: "Ajouter manuellement",
    cancel: "Annuler",
    save: "Enregistrer",
    delete: "Supprimer",
    sign_in: "Se connecter",
    brand: "Marque / Maison",
    name: "Nom",
    rating: "Note",
    library_title: "La Bibliothèque",
    library_subtitle: "Explorez notre collection de fragrances d'exception.",
    loading_more: "Chargement de nouveaux parfums...",
    end_of_collection: "Vous avez atteint la fin de la collection",
    no_fragrances: "Aucun parfum trouvé.",
    clear_filters: "Effacer les filtres",
    top_notes: "Notes de Tête",
    middle_notes: "Notes de Coeur",
    base_notes: "Notes de Fond",
    main_accords: "Accords Principaux",
    release_year: "Année de sortie",
    gender: "Genre",
    men: "Homme",
    women: "Femme",
    unisex: "Unisexe",
    all: "Tous",
    added_to_vault: "Ajouté à la Collection",
    added_to_wishlist: "Ajouté à la Wishlist",
    oxidation_high: "Oxydation Élevée",
    oxidation_mod: "Oxydation Modérée",
    oxidation_stable: "Stable",
    scent_profile: "Profil Olfactif",
    perfumer_phrase: "Le nez derrière ce parfum est",
    // Accords mapping
    "warm spicy": "Épicé chaud",
    "fresh spicy": "Épicé frais",
    "woody": "Boisé",
    "aromatic": "Aromatique",
    "vanilla": "Vanille",
    "citrus": "Agrumes",
    "powdery": "Poudré",
    "floral": "Floral",
    "white floral": "Fleurs blanches",
    "musky": "Musqué",
    "sweet": "Sucré",
    "amber": "Ambré",
    "balsamic": "Balsamique",
    "green": "Vert",
    "fruity": "Fruité",
    "aquatic": "Aquatique",
    "earthy": "Terreux",
    "patchouli": "Patchouli",
    "leather": "Cuir",
    "oud": "Oud",
    "rose": "Rose",
    "smoky": "Fumé",
    "animalic": "Animal",
    "yellow floral": "Fleurs jaunes",
    "tuberose": "Tubéreuse",
    "coniferous": "Conifère",
    "mossy": "Moussu",
    // Notes mapping
    "lavender": "Lavande",
    "bergamot": "Bergamote",
    "mandarin orange": "Mandarine",
    "jasmine": "Jasmin",
    "sandalwood": "Santal",
    "cedar": "Cèdre",
    "musk": "Musc",
    "lemon": "Citron",
    "apple": "Pomme",
    "pink pepper": "Poivre rose",
    "cardamom": "Cardamome",
    "vetiver": "Vétiver",
    "tonka bean": "Fève tonka",
    "neroli": "Néroli",
    "violet": "Violette",
    "geranium": "Géranium",
    "incense": "Encens",
    "saffron": "Safran",
    "cinnamon": "Cannelle",
    "ginger": "Gingembre",
    "grapefruit": "Pamplemousse",
    "pear": "Poire",
    "peach": "Pêche",
    "raspberry": "Framboise",
    "black currant": "Cassis",
    "mint": "Menthe",
    "basil": "Basilic",
    "sage": "Sauge",
    "rosemary": "Romarin",
    "oakmoss": "Mousse de chêne",
    "tobacco": "Tabac",
    "coffee": "Café",
    "chocolate": "Chocolat",
    "honey": "Miel",
    "sea salt": "Sel de mer",
    "coconut": "Noix de coco",
    "pineapple": "Ananas",
    "cherry": "Cerise",
    "orange blossom": "Fleur d'oranger",
    "lily-of-the-valley": "Muguet",
    "benzoin": "Benjoin",
    "myrrh": "Myrrhe",
    "rhubarb": "Rhubarbe",
    "fig": "Figue",
    "petitgrain": "Petitgrain",
    "clary sage": "Sauge sclarée",
    "coriander": "Coriandre",
    "nutmeg": "Noix de muscade",
    "cloves": "Clou de girofle",
    "star anise": "Anis étoilé",
    "licorice": "Réglisse",
    "rum": "Rhum",
    "guaiac wood": "Bois de gaïac",
    "birch": "Bouleau",
    "oak": "Chêne",
    "almond": "Amande",
    "pistachio": "Pistache",
    "hazelnut": "Noisette",
    "tea": "Thé",
    "black tea": "Thé noir",
    "green tea": "Thé vert",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("fr");

  useEffect(() => {
    const saved = localStorage.getItem("scent_lang") as Language;
    if (saved && (saved === "en" || saved === "fr")) {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("scent_lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations["en"]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
}
